name: 打包pg数据库、php前端docker

on:
  workflow_dispatch:
permissions:
  contents: write 
  packages: write 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: setup qemu
      uses: docker/setup-qemu-action@v3
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3
    - name: login docker hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: login github container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        echo "build_tag=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        provenance: false
        platforms: linux/amd64,linux/s390x,linux/arm64,linux/arm/v6
        push: true
        tags: |
          docker.io/${{ github.repository_owner }}/bandwidthd-php:latest
          docker.io/${{ github.repository_owner }}/bandwidthd-php:${{ env.build_tag }}
          ghcr.io/${{ github.repository_owner }}/bandwidthd-php:latest
          ghcr.io/${{ github.repository_owner }}/bandwidthd-php:${{ env.build_tag }}
    - name: Save Docker Image
      run: |
          mkdir -p /opt/dk
          docker pull --platform linux/amd64 lmq8267/bandwidthd-php:latest
          docker save -o /opt/dk/bandwidthd-php-x86_64-docker.tar lmq8267/bandwidthd-php:latest

          docker pull --platform linux/s390x lmq8267/bandwidthd-php:latest
          docker save -o /opt/dk/bandwidthd-php-s390x-docker.tar lmq8267/bandwidthd-php:latest
          
          docker pull --platform linux/arm64 lmq8267/bandwidthd-php:latest
          docker save -o /opt/dk/bandwidthd-php-arm64-docker.tar lmq8267/bandwidthd-php:latest

          # docker pull --platform linux/riscv64 lmq8267/bandwidthd-php:latest
          # docker save -o /opt/dk/bandwidthd-php-riscv64-docker.tar lmq8267/bandwidthd-php:latest

          docker pull --platform linux/arm/v6 lmq8267/bandwidthd-php:latest
          docker save -o /opt/dk/bandwidthd-php-armv6-docker.tar lmq8267/bandwidthd-php:latest

    - name: 上传离线镜像包
      uses: actions/upload-artifact@v4
      with:
        name: bandwidthd-php_Docker
        path: /opt/dk/*

